name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Vérifier les fichiers essentiels
      run: |
        for file in index.html default.conf Dockerfile; do
          if [ ! -f "$file" ]; then
            echo "Erreur: $file manquant!"
            exit 1 
          fi
        done 

    - name: Build Docker image
      run: docker build -t nginx-ci-demo .

    - name: Test Nginx configuration
      run: docker run --rm nginx-ci-demo nginx -t

      #PARTIE1
    # - name: Run Nginx container
    #   run: |
    #     docker run -d --name nginx-test -p 8080:80 nginx-ci-demo
    #     sleep 5
    #     curl -f http://localhost:8080 || exit 1

      #PARTIE2
    - name: Run Nginx container & Test HTTP
      run: |
        docker run -d --name nginx-test -p 8080:80 nginx-ci-demo
        sleep 5
        
        curl -f http://localhost:8080 || exit 1

        curl -f http://localhost:8080/health || exit 1  

      #Partie3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{secrets.GHCR_USERNAME}}
        password: ${{secrets.GHCR_TOKEN}}

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/nginx-ci-demo:${{ github.sha }}    